from pathlib import Path
import hashlib
import json
import shutil
import subprocess

root = Path.cwd()
evidence = Path('/Users/christiandonovan/.no-mistakes/evidence/01M25ZVQSGARNT9VRNTXKY10NY')
scratch = root / '.test-tmp' / 'cli-evidence'
scratch.mkdir()
emitter = root / 'bin/fm-agent-context.py'
transcript = []
def run(args, expected=0, show=True):
    args = [str(x) for x in args]
    result = subprocess.run(args, capture_output=True, text=True)
    if show:
        transcript.extend(['$ ' + ' '.join(args).replace(str(root) + '/', ''), result.stdout.rstrip(), result.stderr.rstrip(), f'exit: {result.returncode}', ''])
    assert result.returncode == expected, (args, result)
    return result

def cli(repo, mode, *extra, expected=0):
    return run([emitter, mode, '--repo', repo, *extra], expected)

def digest(data):
    return hashlib.sha256(data).hexdigest()

context = '''context_state: validated
external_system:
  name: Fixture ERP
  category: ERP
  integration_surface: REST
operator_persona:
  role: operator
  responsibilities:
    - reconcile
domain_summary: Disposable satellite domain
entities:
  - name: Order
    attributes:
      - id
    source_of_truth: ERP
    sensitivity: HIGH
events:
  - name: order.changed
    description: order changed
    payload_fields:
      - id
mcp_tools:
  - name: search_orders
    description: search orders
    access: read
tier:
  level: 1
  rationale: fixture
standalone_face:
  execution_face: worker
  decision_face: operator
write_posture:
  phase: phase_1_pull_only
  approved_entities: []
operator_owned_fields: []
canonical_fields:
  - id
tenants:
  primary: primary
  secondary_sandbox: sandbox
access_model:
  users:
    - operator
  roles:
    - reader
  entitlements:
    - orders.read
operator_decision:
  decision: proceed
  signer_role: operator
  signed_at: "2026-09-10"
  notes: fixture
'''
begin, end = b'<!-- AGENT-CONTEXT:BEGIN -->', b'<!-- AGENT-CONTEXT:END -->'
run([emitter, '--help'])
for kind in ('satellite', 'non-satellite'):
    transcript.append('=== Disposable ' + kind + ' source and clone ===')
    source = scratch / (kind + '-source')
    source.mkdir()
    run(['git', '-C', source, 'init', '-q'], show=False)
    (source / 'README.md').write_text('# Disposable review fixture\n')
    (source / 'package.json').write_text('{"scripts":{"start":"node server.js"}}\n')
    legacy = '# Operator prose above\n\n'
    if kind == 'satellite':
        (source / 'context.yaml').write_text(context)
        (source / 'context.schema.json').write_text(json.dumps({'type': 'object', 'properties': {'domain_summary': {'type': 'string', 'minLength': 10}}}))
        legacy += '<!-- DOMAIN SPECIALIZATION:BEGIN -->\nOld domain facts\n<!-- DOMAIN SPECIALIZATION:END -->\n\n'
    legacy += '<!-- GROUND-TRUTH:BEGIN generated by legacy -->\nOld measured facts\n<!-- GROUND-TRUTH:END -->\n\n# Operator prose below\n'
    (source / 'AGENTS.md').write_text(legacy)
    run(['git', '-C', source, 'add', '.'], show=False)
    run(['git', '-C', source, '-c', 'user.name=Test', '-c', 'user.email=test@example.invalid', 'commit', '-qm', 'disposable source'], show=False)
    repo = scratch / (kind + '-copy')
    run(['git', 'clone', '-q', '--no-local', source, repo])
    remote = 'https://user:token@example.test/org/repo.git' if kind == 'satellite' else 'https://example.test/org/repo.git'
    run(['git', '-C', repo, 'remote', 'set-url', 'origin', remote])
    agents = repo / 'AGENTS.md'
    original = agents.read_bytes()
    (evidence / (kind + '-before.md')).write_bytes(original)
    cli(repo, 'emit', expected=1)
    assert agents.read_bytes() == original
    cli(repo, 'emit', '--migrate-legacy')
    generated = agents.read_bytes()
    assert generated.count(begin) == generated.count(end) == 1
    assert b'DOMAIN SPECIALIZATION:BEGIN' not in generated and b'GROUND-TRUTH:BEGIN' not in generated
    assert generated.startswith(b'# Operator prose above\n\n') and generated.endswith(b'\n\n# Operator prose below\n')
    assert b'user:token' not in generated
    assert (b'https://<redacted>@example.test/org/repo.git' if kind == 'satellite' else remote.encode()) in generated
    assert (b'Disposable satellite domain' if kind == 'satellite' else b'No validated context.yaml is configured') in generated
    (evidence / (kind + '-after.md')).write_bytes(generated)
    transcript.extend(['Generated AGENTS.md:', generated.decode(), ''])
    cli(repo, 'check')
    cli(repo, 'emit')
    assert agents.read_bytes() == generated
    transcript.append('Repeat emission SHA-256 (both runs): ' + digest(generated))
    cli(repo, 'emit', '--migrate-legacy', expected=1)
    assert agents.read_bytes() == generated
    (repo / 'package.json').write_text('{"scripts":{"start":"node changed.js"}}\n')
    cli(repo, 'check', expected=1)
    assert agents.read_bytes() == generated
    transcript.append('Compare-only drift preserved AGENTS.md SHA-256: ' + digest(generated))
    cli(repo, 'emit')
    cli(repo, 'check')
    corrected = agents.read_bytes()
    assert b'node changed.js' in corrected
    if kind == 'satellite':
        (repo / 'context.yaml').write_text(context.replace('Disposable satellite domain', 'x'))
        cli(repo, 'emit', expected=1)
        assert agents.read_bytes() == corrected
        (repo / 'context.yaml').write_text(context)
        (repo / 'context.schema.json').write_text('{"properties":{"absent":{"pattern":"x"}}}')
        cli(repo, 'emit', expected=1)
        assert agents.read_bytes() == corrected
        shutil.copyfile(source / 'context.schema.json', repo / 'context.schema.json')
    for label, bad in [('malformed', begin + b'\nunterminated\n'), ('duplicate', corrected + begin + b'\nsecond\n' + end)]:
        agents.write_bytes(bad)
        for mode in ('emit', 'check'):
            cli(repo, mode, expected=1)
            assert agents.read_bytes() == bad
        transcript.append(label + ' refusal preserved exact input bytes')
    agents.write_bytes(corrected)
    (repo / 'package.json').write_text(json.dumps({'scripts': {'start': "echo '<!-- AGENT-CONTEXT:END -->'"}}))
    cli(repo, 'emit')
    cli(repo, 'check')
    escaped = agents.read_bytes()
    assert escaped.count(begin) == escaped.count(end) == 1
    assert b'&lt;!-- AGENT-CONTEXT:END -->' in escaped
    transcript.append('Generated escaped entrypoint: ' + next(line for line in escaped.decode().splitlines() if line.startswith('- Entrypoints:')))
    assert (source / 'AGENTS.md').read_bytes() == original
    status = run(['git', '-C', source, 'status', '--porcelain'], show=False)
    assert not status.stdout
    transcript.append('Original disposable source remains byte-identical and clean.\n')
(evidence / 'cli-transcript.txt').write_text('\n'.join(transcript))
shutil.rmtree(scratch)
print('CLI walkthrough completed; transcript and before/after generated files saved.')
