"""Replay public CLI acceptance checks; scratch repositories stay in this worktree."""
from pathlib import Path
import hashlib
import json
import re
import shlex
import shutil
import subprocess
import tempfile

root = Path.cwd()
evidence = Path('/Users/christiandonovan/.no-mistakes/evidence/01M25V752NXJK6AXNFHGG7SZJZ')
emitter = root / 'bin/fm-agent-context.py'
log = []
def run(args, expected=0):
    result = subprocess.run([str(a) for a in args], text=True, capture_output=True)
    log.extend(['$ ' + shlex.join(str(a) for a in args), result.stdout.rstrip(), result.stderr.rstrip(), f'exit: {result.returncode}', ''])
    assert result.returncode == expected, result
    return result

def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()

def emit(repo, *flags, expected=0):
    return run([emitter, 'emit', '--repo', repo, *flags], expected)

def check(repo, expected=0):
    return run([emitter, 'check', '--repo', repo], expected)

with tempfile.TemporaryDirectory(prefix='manual-', dir=root / '.test-agent-context-tmp') as tmp:
    tmp = Path(tmp)
    # Reuse the suite's declarative domain fixtures as input, not as assertions.
    fixture_source = (root / 'tests/fm-agent-context.test.sh').read_text()
    schema = json.loads(re.search(r'cat > "\$1/context.schema.json" <<\'EOF\'\n(.*?)\nEOF', fixture_source, re.S)[1])
    context = json.loads(re.search(r'cat > "\$1/context.yaml" <<\'EOF\'\n(.*?)\nEOF', fixture_source, re.S)[1])
    # Exercise actual block YAML mappings, lists, and scalar types through the CLI.
    def yaml_lines(value, indent=0):
        pad = ' ' * indent
        lines = []
        for key, item in value.items():
            if isinstance(item, dict):
                lines += [pad + key + ':'] + yaml_lines(item, indent + 2)
            elif isinstance(item, list) and item:
                lines.append(pad + key + ':')
                for entry in item:
                    if isinstance(entry, dict):
                        nested = yaml_lines(entry, indent + 4)
                        lines += [pad + '  - ' + nested[0].lstrip()] + nested[1:]
                    else:
                        lines.append(pad + '  - ' + json.dumps(entry))
            else:
                lines.append(pad + key + ': ' + json.dumps(item))
        return lines

    for kind in ('satellite', 'non-satellite'):
        source, repo = tmp / (kind + '-source'), tmp / (kind + '-copy')
        source.mkdir()
        run(['git', '-C', source, 'init', '-q'])
        (source / 'README.md').write_text('# Disposable acceptance fixture\n')
        (source / 'package.json').write_text(json.dumps({'scripts': {'start': 'node server.js'}}))
        legacy = '<!-- GROUND-TRUTH:BEGIN generated by legacy -->\nold measured facts\n<!-- GROUND-TRUTH:END -->'
        if kind == 'satellite':
            (source / 'context.schema.json').write_text(json.dumps(schema))
            (source / 'context.yaml').write_text('\n'.join(yaml_lines(context)) + '\n')
            legacy = '<!-- DOMAIN SPECIALIZATION:BEGIN -->\nold domain facts\n<!-- DOMAIN SPECIALIZATION:END -->\n\nHuman prose between generated regions.\n\n' + legacy
        original = ('# Human prose above\n\n' + legacy + '\n\n# Human prose below\n').encode()
        (source / 'AGENTS.md').write_bytes(original)
        run(['git', '-C', source, 'add', '.'])
        run(['git', '-C', source, '-c', 'user.name=Acceptance Test', '-c', 'user.email=test@example.invalid', 'commit', '-qm', 'fixture'])
        run(['git', 'clone', '-q', '--no-local', source, repo])
        run(['git', '-C', repo, 'remote', 'set-url', 'origin', 'https://user:token@example.test/org/repo.git'])
        agents = repo / 'AGENTS.md'
        check(repo, 1)
        emit(repo, expected=1)
        assert agents.read_bytes() == original
        emit(repo, '--migrate-legacy')
        migrated = agents.read_bytes()
        assert migrated.count(b'<!-- AGENT-CONTEXT:BEGIN -->') == migrated.count(b'<!-- AGENT-CONTEXT:END -->') == 1
        assert b'user:token' not in migrated and b'<redacted>@example.test' in migrated
        assert migrated.startswith(b'# Human prose above\n\n') and migrated.endswith(b'\n\n# Human prose below\n')
        if kind == 'satellite':
            assert b'Human prose between generated regions.' in migrated and b'Fixture ERP' in migrated
        else:
            assert b'No validated context.yaml is configured' in migrated
        shutil.copyfile(agents, evidence / (kind + '-AGENTS.md'))
        emit(repo, '--migrate-legacy', expected=1)
        assert agents.read_bytes() == migrated
        check(repo)
        before = digest(agents)
        emit(repo)
        assert digest(agents) == before
        log.append(f'Repeat byte identity ({kind}): SHA-256 {before}')
        (repo / 'package.json').write_text(json.dumps({'scripts': {'start': 'node changed.js'}}))
        check(repo, 1)
        assert digest(agents) == before
        log.append(f'Compare-only drift preserved AGENTS.md: SHA-256 {digest(agents)}')
        emit(repo)
        check(repo)
        assert b'node changed.js' in agents.read_bytes()
        if kind == 'satellite':
            schema['properties']['domain_summary']['minLength'] = 100
            (repo / 'context.schema.json').write_text(json.dumps(schema))
            before = digest(agents)
            emit(repo, expected=1)
            assert digest(agents) == before
            del schema['properties']['domain_summary']['minLength']
            schema['properties']['absent'] = {'pattern': '^x$'}
            (repo / 'context.schema.json').write_text(json.dumps(schema))
            emit(repo, expected=1)
            assert digest(agents) == before
            del schema['properties']['absent']
            (repo / 'context.schema.json').write_text(json.dumps(schema))
        (repo / 'package.json').write_text(json.dumps({'scripts': {'start': "echo '<!-- AGENT-CONTEXT:END -->'"}}))
        emit(repo)
        check(repo)
        assert agents.read_bytes().count(b'<!-- AGENT-CONTEXT:END -->') == 1
        assert b'&lt;!-- AGENT-CONTEXT:END -->' in agents.read_bytes()
        shutil.copyfile(agents, evidence / (kind + '-escaped-markers-AGENTS.md'))
        valid = agents.read_bytes()
        for malformed in (b'<!-- AGENT-CONTEXT:BEGIN -->\nunterminated\n', valid + valid):
            agents.write_bytes(malformed)
            emit(repo, expected=1)
            check(repo, 1)
            assert agents.read_bytes() == malformed
        agents.write_bytes(valid)
        run(['git', '-C', repo, 'remote', 'set-url', 'origin', 'https://example.test/org/repo.git'])
        emit(repo)
        assert b'https://example.test/org/repo.git' in agents.read_bytes()
        log.append('Ordinary-origin positive control in generated AGENTS.md: https://example.test/org/repo.git')
        assert (source / 'AGENTS.md').read_bytes() == original
        assert not run(['git', '-C', source, 'status', '--porcelain']).stdout
        log.append(f'{kind} migration source remains unchanged. Only its disposable clone was migrated.\n')
    result = run([emitter, '--help'])
    assert 'unchanged in cost' in result.stdout
    log.append('Tenant scope: third-tenant work remains unchanged in cost; schema and renderer migration are still required.')
(evidence / 'agent-context-cli-transcript.txt').write_text('\n'.join(line for line in log if line != '') + '\n')
print('Saved CLI transcript and actual generated AGENTS.md evidence; all public CLI assertions passed.')
