from pathlib import Path
import os,subprocess,shlex
root=Path('/Users/christiandonovan/.no-mistakes/worktrees/d9c4fb60435f/01M2HFBS0PSJJP586FSE1NY79C'); ev=Path('/Users/christiandonovan/.no-mistakes/evidence/01M2HFBS0PSJJP586FSE1NY79C')
env={k:v for k,v in os.environ.items() if not k.startswith(('FM_', 'TASKS_AXI_', 'GIT_'))};env.update(HOME=str(root/'.test-phase/home'),TMPDIR=str(root/'.test-phase/tmp'),GIT_CONFIG_NOSYSTEM='1',GIT_CONFIG_GLOBAL='/dev/null',GIT_AUTHOR_NAME='Isolated validation',GIT_COMMITTER_NAME='Isolated validation',GIT_AUTHOR_EMAIL='test@example.invalid',GIT_COMMITTER_EMAIL='test@example.invalid')
with (ev/'refusal-controls.log').open('w') as log:
 def run(args,cwd=root,rc=0):
  r=subprocess.run(list(map(str,args)),cwd=cwd,env=env,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True,timeout=60)
  log.write('$ '+shlex.join(list(map(str,args)))+'\n'+r.stdout+'[exit '+str(r.returncode)+']\n\n');log.flush()
  assert r.returncode==rc,(r.returncode,r.stdout);return r.stdout
 repo=root/'.test-phase/live/history'
 run(['git','checkout','-qb','divergent-control','c781bb13857b76210faf2ff8288b9a0bcaedc4ef'],cwd=repo)
 (repo/'local-work.txt').write_text('Unlanded local work must survive.\n')
 run(['git','add','local-work.txt'],cwd=repo);run(['git','commit','-qm','isolated divergent work'],cwd=repo)
 before=run(['git','rev-parse','HEAD'],cwd=repo)
 run(['git','merge','--ff-only','c6c1c64f11188a1190db75522545ff2478ae1b88'],cwd=repo,rc=128)
 assert run(['git','rev-parse','HEAD'],cwd=repo)==before
 assert (repo/'local-work.txt').read_text()=='Unlanded local work must survive.\n'
 # The standalone emitter never migrates legacy generated text without the flag.
 repo=root/'.test-phase/live/emitter'; agent=repo/'AGENTS.md'
 original=b'# Human prose above\n<!-- GROUND-TRUTH:BEGIN generated by legacy -->\nold measured content\n<!-- GROUND-TRUTH:END -->\n# Human prose below\n'
 agent.write_bytes(original);cli=root/'bin/fm-agent-context.py'
 run([cli,'emit','--repo',repo],rc=1);assert agent.read_bytes()==original
 run([cli,'emit','--migrate-legacy','--repo',repo]);run([cli,'check','--repo',repo])
 migrated=agent.read_bytes();assert migrated.startswith(b'# Human prose above\n') and b'# Human prose below\n' in migrated
 run([cli,'emit','--migrate-legacy','--repo',repo],rc=1);assert agent.read_bytes()==migrated
 (repo/'context.yaml').write_text('{"context_state":"validated"}')
 run([cli,'emit','--repo',repo],rc=1);assert agent.read_bytes()==migrated
 (ev/'migrated-agent-context.md').write_bytes(migrated)
 log.write('Divergent history remained intact; legacy migration was explicit and one-time; missing schema refused without writing.\n')
print('Divergence and emitter refusal controls passed')
